### ISSUE TITLE
socket.error: [Errno 99] Cannot assign requested address

### ISSUE THREAD

**Issue by xuying156209** [ziggear/shadowsocks#10]
after install the sock, i type the command line like this   "ssserver -s remote_server_address -p my_port -k my_password -m rc4-md5" ,and i got the error below.       

- Traceback (most recent call last):
  File "/usr/local/bin/ssserver", line 11, in <module>
    load_entry_point('shadowsocks==2.8.2', 'console_scripts', 'ssserver')()
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks/server.py", line 68, in main
    tcp_servers.append(tcprelay.TCPRelay(a_config, dns_resolver, False))
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks/tcprelay.py", line 582, in __init__
    server_socket.bind(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address

**Comment by spectrometerHBH** [comment]
I have the same problem with you. Have you solved it?
