### ISSUE TITLE
问个简单的问题

### ISSUE THREAD

**Issue by DorianZheng** [ziggear/shadowsocks#3]
既然SOCKS5协议会把对端ip和port放在头部，那么GFW不是可以通过检测头部的ip和port来判断是否访问的被禁网站吗？

**Comment by Siubaak** [comment]
所以sslocal和ssserver之间需要加密呗

**Comment by jiesince1998** [comment]
INFO: loading config from /etc/shadowsocks/config.json
shadowsocks 2.1.0
2017-10-08 18:42:52 INFO     starting server at 138.68.236.26:8388
Traceback (most recent call last):
  File "/usr/bin/ssserver", line 9, in <module>
    load_entry_point('shadowsocks==2.1.0', 'console_scripts', 'ssserver')()
  File "/usr/lib/python2.7/dist-packages/shadowsocks/server.py", line 66, in main
    tcp_servers.append(tcprelay.TCPRelay(a_config, dns_resolver, False))
  File "/usr/lib/python2.7/dist-packages/shadowsocks/tcprelay.py", line 519, in __init__
    server_socket.bind(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address



有人知道这是什么问题吗

**Comment by HenryZhou1002** [comment]
请问多用户多端口应该在哪里设置呢？
