### ISSUE TITLE
shadowsocks运行出错

### ISSUE THREAD

**Issue by jiesince1998** [ziggear/shadowsocks#4]
INFO: loading config from /etc/shadowsocks/config.json
shadowsocks 2.1.0
2017-10-08 18:42:52 INFO     starting server at 138.68.236.26:8388
Traceback (most recent call last):
  File "/usr/bin/ssserver", line 9, in <module>
    load_entry_point('shadowsocks==2.1.0', 'console_scripts', 'ssserver')()
  File "/usr/lib/python2.7/dist-packages/shadowsocks/server.py", line 66, in main
    tcp_servers.append(tcprelay.TCPRelay(a_config, dns_resolver, False))
  File "/usr/lib/python2.7/dist-packages/shadowsocks/tcprelay.py", line 519, in __init__
    server_socket.bind(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address

什么原因呢?    
这个是我的配置文件, 密码已隐藏:
{
    "server":"2604:a880:2:d0::4fea:5001",
    "server_port":3024,
    "local_address": "127.0.0.1",
    "local_port":1080,
    "password":"********",
    "timeout":300,
    "method":"aes-256-cfb",
    "fast_open": true,
    "workers": 1
}

**Comment by kongds** [comment]
It seems can't work with ipv6. Change `server` to ipv4 or set `server` to "::0".

**Comment by jiesince1998** [comment]
但是我在Windows系统下配置shadowsocks的时候用的也是ipv6, 没有一点问题啊.
更改成ivp4还是不行

**Comment by LiaoJingyi** [comment]
ssserver is for server. You are client.
Qt is more friendly for beginner.

**Comment by LiaoJingyi** [comment]
FYI

https://wiki.archlinux.org/index.php/Shadowsocks#Client
